services:
  apache:
    build: .
    ports:
      - "${BODY_PORT}:80"
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: ${BODY_URL}
      DB_HOST: db
      DB_NAME: body
      DB_USER: body
      DB_PASSWORD: body
  db:
    image: postgres:18.4
    environment:
      POSTGRES_PASSWORD: body
      POSTGRES_USER: body
